language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5

env:
    - DOCTRINE_BRIDGE_VERSION=2.3
    - DOCTRINE_BRIDGE_VERSION=2.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - if [ $(php -v | grep '5.3.3' -c) -ne 0 ]; then export PREFER="--prefer-source"; else PREFER="--prefer-dist"; fi
    - php composer.phar require symfony/doctrine-bridge:${DOCTRINE_BRIDGE_VERSION} ${PREFER}

notifications:
    email:
        - tomas@pecserke.eu
